# Generated by Django 5.1.3 on 2025-07-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_settingsmodel_created_at_settingsmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionsmodel',
            name='key',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='key',
            field=models.CharField(db_index=True, unique=True, verbose_name='key'),
        ),
    ]
