# Generated by Django 5.1.3 on 2025-06-24 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField(verbose_name='amount')),
                ('currency', models.PositiveIntegerField(default=860, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('canceled', 'canceled')], default='pending', max_length=20, verbose_name='status')),
                ('provider', models.CharField(choices=[('paylov', 'paylov')], verbose_name='payment provider')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordermodel', verbose_name='order')),
            ],
            options={
                'verbose_name': 'PaylovtransactionModel',
                'verbose_name_plural': 'PaylovtransactionModels',
                'db_table': 'paylovTransaction',
            },
        ),
    ]
