# Generated by Django 5.1.3 on 2025-06-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemsmodel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitemsmodel',
            name='count',
            field=models.IntegerField(default=1, verbose_name='count'),
        ),
        migrations.AddField(
            model_name='orderitemsmodel',
            name='discount',
            field=models.FloatField(default=-1.0, verbose_name='discount'),
        ),
    ]
