# Generated by Django 5.1.3 on 2025-06-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cartmodel_user_alter_orderitemsmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('canceled', 'canceled')], default='pending', verbose_name='payment status'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='created', max_length=20, verbose_name='status'),
        ),
    ]
