# Generated by Django 5.1.3 on 2025-07-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ordermodel_payment_status_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_notify',
            field=models.BooleanField(default=False, verbose_name='Is Notify'),
        ),
    ]
