# Generated by Django 5.1.3 on 2025-07-11 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_productmodel_description_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='first_name',
            field=models.CharField(blank=True, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='last_name',
            field=models.CharField(blank=True, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(blank=True, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
