# Generated by Django 5.1.3 on 2025-07-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ordermodel_address_ordermodel_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='address',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='city',
            field=models.CharField(blank=True, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='comment',
            field=models.CharField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='company_name',
            field=models.CharField(blank=True, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='district',
            field=models.CharField(blank=True, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='region',
            field=models.CharField(blank=True, null=True, verbose_name='Region'),
        ),
    ]
