# Generated by Django 5.1.3 on 2025-08-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_ordermodel_address_ordermodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='amount'),
        ),
    ]
